import './globals.css'
import type {Metadata} from 'next'
import Header from "@/components/Header/Header";
import {ReduxProvider} from "@/redux/provider/provider";
import { Roboto } from 'next/font/google'

const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'My social site',
    description: 'Generated by create next app',
}


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={roboto.className}>
        <ReduxProvider>
            <Header/>
            <div className='wrap'>
            {children}
            </div>
        </ReduxProvider>
        </body>
        </html>
    )
}
