
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/Header/Header";
import styleApp from "@/app/page.module.css";
import styleAside from "@/components/Aside/Aside.module.css";
import Aside from "@/components/Aside/Aside";
import styleMain from "@/components/Main/Main.module.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My social site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <div className={styleApp.container}>
        <aside className={styleAside.aside}>
          <Aside/>
        </aside>
        <main className={styleMain.main}>
          {children}
        </main>
      </div>
      </body>
    </html>
  )
}
