import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Header from "@/components/Header/Header";
import {ReduxProvider} from "@/redux/provider/provider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'My social site',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ReduxProvider>
            <Header/>
            {children}
        </ReduxProvider>
        </body>
        </html>
    )
}
